var config={
    resource:{//系统所用的资源
        font:"Panorama/Font/FZYaoTi_Regular.json",//字体的json文件的地址
        image:[//系统用到的image资源
            {name:"direct",url:"Panorama/Image/arrow.png"}//hotspot默认使用该图标
        ]
    },
    autoPlay:{//自动播放（跳转）
        default:{
            use:true,//是否开启自动播放功能
            timeOut:500,//跳转间隔,单位毫秒，1000毫秒为1秒
        },
        queue:[//自动切换场景时的场景序列
            {name:"街景000"},
            {name:"街景001"},
            {name:"街景002"},
            {name:"街景003"},
            {name:"街景004"},
            {name:"街景005"},
            {name:"街景006"},
            {name:"街景007"},
            {name:"街景008"},
            {name:"街景009"},
        ]
    },
    scenes:{
        default:{
            name:"街景000",//默认的场景名称
            view:{hlookat:0,vlookat:0},
            hotspots:{ath:0,atv:-30}//为hotspot配了默认值，marks没有，因为mark横竖位置都不固定
        },
        list:[
        {//一个场景
            name:"呈坎01",//名称
            image:"Panorama/Image/黄山市呈坎/0101.jpg",//全景图片的url地址
            view:{hlookat:15},//进入场景时的角度
            hotspots:[//场景中出现的热点,热点指向下一个场景，name为场景名
                //{ath:180,atv:0,name:"呈坎01"},//热点的水平面角度和垂直面角度值，正方向为从Y轴正方向向负方向俯瞰XZ平面，从X轴正方向逆时针旋转为正
                {ath:90,name:"呈坎02",scale:1.5,image:"direct"} //atv:[-90,90],ath:[0,360],此处使用了image标签，是为了演示，默认都是用direct图片
            ],
            audio:"",//解说音频文件的url
            summay:"",//场景的简介
            marks:[//场景中的标注，如标注是什么山，什么大坝等，标注是纯文字标注，不再使用图片
                {ath:340,atv:-15,text:"居民区",image:"direct"},//mark标注也可以用图片
                {ath:340,atv:-30,text:"高速公路"},
                {ath:120,atv:-5,text:"山峰"},
                {ath:172,atv:-25,text:"道路"},
                {ath:264,atv:-12,text:"广告牌"}
            ],
        },
        {//一个场景
            name:"呈坎02",//名称
            image:"Panorama/Image/黄山市呈坎/0102.jpg",//全景图片的url地址
            view:{hlookat:15},//进入场景时的角度
            hotspots:[//场景中出现的热点
                {ath:120,atv:-20,name:"呈坎01"},
                {ath:270,atv:-20,name:"呈坎03"}
            ],
            audio:"",//解说音频文件的url
            summay:"",//场景的简介
            marks:[//场景中的标注，如标注是什么山，什么大坝等，标注是纯文字标注，不再使用图片
                {ath:150,atv:0,text:"远山"}
            ],
        },
        {//一个场景
            name:"呈坎03",//名称
            image:"Panorama/Image/黄山市呈坎/0103.jpg",//全景图片的url地址
            view:{hlookat:15},//进入场景时的角度
            hotspots:[//场景中出现的热点
                {ath:0,atv:-20,name:"呈坎02"},
                {ath:90,atv:-20,name:"呈坎04"}
            ],
            audio:"",//解说音频文件的url
            summay:""//场景的简介
        },
        {//一个场景
            name:"呈坎04",//名称
            image:"Panorama/Image/黄山市呈坎/0104.jpg",//全景图片的url地址
            view:{hlookat:15},//进入场景时的角度
            hotspots:[//场景中出现的热点
               // {ath:12,atv:12,name:""},
                {ath:120,atv:-20,name:"呈坎03"}
            ],
            audio:"",//解说音频文件的url
            summay:""//场景的简介
        },  
        {//一个场景
            name:"街景000",//名称
            image:"Panorama/Image/街景/posed000000.jpg",//全景图片的url地址
            view:{hlookat:270},//进入场景时的角度
            
            audio:"",//解说音频文件的url
            summay:""//场景的简介
        },
        {//一个场景
            name:"街景001",//名称
            image:"Panorama/Image/街景/posed000001.jpg",//全景图片的url地址
            view:{hlookat:270},//进入场景时的角度
            
            audio:"",//解说音频文件的url
            summay:""//场景的简介
        },
        {//一个场景
            name:"街景002",//名称
            image:"Panorama/Image/街景/posed000002.jpg",//全景图片的url地址
            view:{hlookat:270},//进入场景时的角度
            
            audio:"",//解说音频文件的url
            summay:""//场景的简介
        },
        {//一个场景
            name:"街景003",//名称
            image:"Panorama/Image/街景/posed000003.jpg",//全景图片的url地址
            view:{hlookat:270},//进入场景时的角度
            
            audio:"",//解说音频文件的url
            summay:""//场景的简介
        },
        {//一个场景
            name:"街景004",//名称
            image:"Panorama/Image/街景/posed000004.jpg",//全景图片的url地址
            view:{hlookat:270},//进入场景时的角度
            
            audio:"",//解说音频文件的url
            summay:""//场景的简介
        },
        {//一个场景
            name:"街景005",//名称
            image:"Panorama/Image/街景/posed000005.jpg",//全景图片的url地址
            view:{hlookat:270},//进入场景时的角度
            
            audio:"",//解说音频文件的url
            summay:""//场景的简介
        },
        {//一个场景
            name:"街景006",//名称
            image:"Panorama/Image/街景/posed000006.jpg",//全景图片的url地址
            view:{hlookat:270},//进入场景时的角度
            
            audio:"",//解说音频文件的url
            summay:""//场景的简介
        },
        {//一个场景
            name:"街景007",//名称
            image:"Panorama/Image/街景/posed000007.jpg",//全景图片的url地址
            view:{hlookat:270},//进入场景时的角度
            
            audio:"",//解说音频文件的url
            summay:""//场景的简介
        },
        {//一个场景
            name:"街景008",//名称
            image:"Panorama/Image/街景/posed000008.jpg",//全景图片的url地址
            view:{hlookat:270},//进入场景时的角度
            
            audio:"",//解说音频文件的url
            summay:""//场景的简介
        },
        {//一个场景
            name:"街景009",//名称
            image:"Panorama/Image/街景/posed000009.jpg",//全景图片的url地址
            view:{hlookat:270},//进入场景时的角度
            
            audio:"",//解说音频文件的url
            summay:""//场景的简介
        }
        
    ]}
    
}